---
from: admin@kopokopo.com
domain: kopokopo.com
strategy: smtp
smtp_settings:
  address: smtp.gmail.com
  port: '587'
  domain: kopokopo.com
  user_name: admin@kopokopo.com
  password: "#111k2admin"
  authentication: plain
  enable_starttls_auto: false
